- name: Backup switch running config to FTP server
  hosts: switches                # Grup host atau host target
  gather_facts: no               # Tidak perlu mengumpulkan fakta
  connection: ssh       # Menetapkan koneksi untuk perangkat jaringan
  tasks:
    - name: Copy running-config to FTP server
      ansible.netcommon.cli_command:
        command: "copy running-config ftp://svra:P%40ssw0rdapl2024.%21@10.12.10.190"
      register: result
