- name: Run show running-config on Cisco Nexus Switch
  hosts: nexus
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Show running-config on Nexus switch
      cisco.nxos.nxos_command:
        commands:
          - show running-config
      register: result

    - name: Display the result
      debug:
        var: result
