- name: Copy configuration from switch to Ubuntu server
  hosts: switches
  gather_facts: no
  become: no

  tasks:
    - name: Run command to export the switch configuration
      command: show running-config
      register: switch_config_output
      # Pastikan perintah ini sesuai dengan yang berlaku di switch Anda
      # Misalnya, jika menggunakan Cisco, perintahnya bisa berbeda seperti 'copy running-config tftp://<server_ip>/config.txt'

    - name: Save the output of the command to a local file
      copy:
        content: "{{ switch_config_output.stdout }}"
        dest: "/tmp/switch_config.txt"

- name: Copy the configuration from the switch to the Ubuntu server
  hosts: ubuntu_server
  gather_facts: no
  become: yes

  tasks:
    - name: Fetch the switch configuration from local to the Ubuntu server
      fetch:
        src: /tmp/switch_config.txt
        dest: /path/to/your/ubuntu/server/configs/
        flat: yes
