- name: Backup switch running config to FTP server using SSH
  hosts: switches
  connection: ssh      # Menggunakan koneksi SSH
  tasks:
    - name: Copy running-config to FTP server
      command: "copy running-config ftp://svra:P%40ssw0rdapl2024.%21@10.12.10.190"
      register: result
