- name: Backup Nexus Cisco
  hosts: nexus

  tasks:
    - name: Backup Nexus Cisco
      cisco.nxos.nxos_config:
        backup: true
        backup_options:
          filename: "backup-1.txt"
          dirpath: /root/snap/semaphore/common/repositories/repository_3_3
